#!/bin/bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch bar1 and bar2
# polybar example &
polybar level -r & 
polybar control -r &
polybar workspace -r &
polybar music -r &
polybar player -r &
polybar close -r &
polybar notify -r &
polybar status -r &
polybar power -r &


